"""Hardware smoke test; it inspects PCM generated by the connected ESP32."""

import argparse
import hashlib
import queue
import struct
import threading
import time

from transport import SerialTransport


def samples(pcm: bytes) -> tuple[int, ...]:
    return struct.unpack(f"<{len(pcm) // 2}h", pcm)


def metrics(pcm: bytes) -> tuple[float, int, float]:
    values = samples(pcm)
    rms = (sum(value * value for value in values) / len(values)) ** 0.5
    peak = max(abs(value) for value in values)
    crossings = sum(a <= 0 < b for a, b in zip(values, values[1:]))
    frequency = crossings / (len(values) / 48_000)
    return rms, peak, frequency


class SmokeTest:
    def __init__(self, port: str) -> None:
        self.audio: queue.Queue[bytes] = queue.Queue(maxsize=500)
        self.statuses: list[dict] = []
        self.status_event = threading.Event()
        self.transport = SerialTransport(self.audio, self._status)
        self.transport.connect(port)
        if not self.status_event.wait(2):
            raise AssertionError("STATUS timeout")

    def _status(self, status: dict) -> None:
        self.statuses.append(status)
        self.status_event.set()

    def send(self, *commands: str) -> None:
        for command in commands:
            self.transport.send(command)

    def drain(self) -> None:
        while True:
            try:
                self.audio.get_nowait()
            except queue.Empty:
                return

    def grab(self, block_count: int) -> bytes:
        return b"".join(
            self.audio.get(timeout=0.3) for _ in range(block_count)
        )

    def settle(self, seconds: float = 0.15) -> None:
        time.sleep(seconds)
        self.drain()

    def run(self) -> None:
        status = self.statuses[-1]
        assert status["protocol"] == 1
        assert status["sampleRate"] == 48_000
        assert status["blockSamples"] == 480
        print("STATUS", status)

        self.send(
            "SET MODE SINE1",
            "SET LFO_SHAPE TRIANGLE",
            "SET LFO_DEPTH_OCT 0",
            "SET ECHO_LEVEL 0",
            "SET MASTER 0.5",
            "SET TUNE_HZ 220",
            "SET DECAY_MS 0",
            "TRIGGER 0",
            "HOLD 0",
            "STREAM 1",
        )
        self.settle()
        rms, _, _ = metrics(self.grab(20))
        assert rms == 0

        self.send("TRIGGER 1")
        self.settle(0.20)
        start = time.perf_counter()
        pcm_220 = self.grab(100)
        elapsed = time.perf_counter() - start
        rms_220, _, hz_220 = metrics(pcm_220)
        assert rms_220 > 5_000 and 217 <= hz_220 <= 223
        assert 0.90 <= elapsed <= 1.08, f"unexpected block timing: {elapsed:.3f}s"

        self.send("SET TUNE_HZ 440")
        self.settle(0.20)
        _, _, hz_440 = metrics(self.grab(80))
        assert 435 <= hz_440 <= 445
        print(
            "PACING_TUNE",
            {"100_blocks_seconds": round(elapsed, 3), "hz": [hz_220, hz_440]},
        )

        self.send("TRIGGER 0")
        self.settle(0.05)
        assert metrics(self.grab(10))[0] == 0
        self.send("HOLD 1")
        self.settle(0.10)
        assert metrics(self.grab(10))[0] > 5_000
        self.send("HOLD 0", "SET TUNE_HZ 220", "SET DECAY_MS 300", "TRIGGER 1")
        self.settle(0.10)
        self.send("TRIGGER 0")
        early_decay = metrics(self.grab(10))[0]
        late_decay = metrics(self.grab(60)[-9_600:])[0]
        assert late_decay < early_decay * 0.35
        print("GATE_ENVELOPE", {"early_rms": early_decay, "late_rms": late_decay})

        self.send("SET DECAY_MS 0", "HOLD 1", "SET LFO_DEPTH_OCT 0")
        mode_hashes = {}
        for mode in ("SINE1", "SINE2", "TEST_TONE", "SQUARE"):
            self.send(f"SET MODE {mode}")
            self.settle(0.08)
            mode_hashes[mode] = hashlib.sha256(self.grab(12)).hexdigest()[:12]
        assert len(set(mode_hashes.values())) == 4
        print("MODES", mode_hashes)

        self.send(
            "SET MODE SINE1",
            "SET LFO_SHAPE MANUAL",
            "SET LFO_DEPTH_OCT 1",
            "SET TUNE_HZ 220",
            "MOD_UP 1",
        )
        self.settle(0.25)
        hz_up = metrics(self.grab(40))[2]
        self.send("MOD_UP 0", "MOD_DOWN 1")
        self.settle(0.25)
        hz_down = metrics(self.grab(40))[2]
        self.send("MOD_UP 1")
        self.settle(0.25)
        hz_both = metrics(self.grab(40))[2]
        assert 430 <= hz_up <= 450
        assert 105 <= hz_down <= 115
        assert 215 <= hz_both <= 225
        self.send("MOD_UP 0", "MOD_DOWN 0")
        print("MANUAL", {"up_hz": hz_up, "down_hz": hz_down, "both_hz": hz_both})

        shape_hashes = {}
        self.send("SET LFO_RATE_HZ 8", "SET LFO_DEPTH_OCT 1")
        for shape in (
            "TRIANGLE",
            "SQUARE",
            "SAW_UP",
            "SAW_DOWN",
            "ASYM_UP",
            "ASYM_DOWN",
            "PULSE_25",
            "PULSE_75",
        ):
            self.send(f"SET LFO_SHAPE {shape}")
            self.settle(0.05)
            shape_hashes[shape] = hashlib.sha256(self.grab(15)).hexdigest()[:12]
        assert len(set(shape_hashes.values())) == 8
        print("LFO_SHAPES", shape_hashes)

        self.send(
            "SET LFO_DEPTH_OCT 0",
            "SET DELAY_MS 50",
            "SET FEEDBACK 0.90",
            "SET ECHO_LEVEL 1",
            "SET HPF_HZ 50",
            "SET LPF_HZ 19000",
            "SET DECAY_MS 0",
            "HOLD 0",
            "TRIGGER 1",
        )
        self.settle(0.20)
        self.send("TRIGGER 0")
        time.sleep(0.06)
        self.drain()
        wet_rms = metrics(self.grab(10))[0]
        self.send("ECHO_CUT 1")
        self.settle(0.10)
        cut_rms = metrics(self.grab(8))[0]
        self.send("ECHO_CUT 0")
        self.settle(0.10)
        restored_rms = metrics(self.grab(8))[0]
        print("ECHO_CUT", {"wet": wet_rms, "cut": cut_rms, "restored": restored_rms})
        assert wet_rms > 50 and cut_rms == 0 and restored_rms > 10

        self.send("SET FEEDBACK 1.05", "TRIGGER 1")
        self.settle(0.10)
        self.send("TRIGGER 0")
        feedback_pcm = self.grab(150)
        feedback_rms, feedback_peak, _ = metrics(feedback_pcm)
        assert feedback_rms > 10 and feedback_peak <= 32767
        self.send("SET HPF_HZ 7000", "SET LPF_HZ 200")
        filtered = self.grab(30)
        assert hashlib.sha256(filtered).digest() != hashlib.sha256(feedback_pcm[: len(filtered)]).digest()
        print("FEEDBACK_FILTERS", {"rms": feedback_rms, "peak": feedback_peak})

        self.send("STREAM 0", "HOLD 0", "TRIGGER 0")
        time.sleep(0.15)
        self.drain()
        time.sleep(0.08)
        assert self.audio.empty()
        self.transport.send("UNKNOWN COMMAND")
        self.status_event.clear()
        self.transport.send("HELLO")
        assert self.status_event.wait(1)
        print("STOP_RESYNC", "ok")

    def close(self) -> None:
        try:
            if self.transport.connected:
                self.transport.send("STREAM 0")
        finally:
            self.transport.disconnect()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("port")
    args = parser.parse_args()
    test = SmokeTest(args.port)
    try:
        test.run()
    finally:
        test.close()


if __name__ == "__main__":
    main()
